### ISSUE TITLE
psbt: crash on checking key type

### ISSUE THREAD

**Issue by brunoerg** [brunoerg/bitcoinfuzz#44]
We just got a crash on psbt target. `rust-miniscript` successfully deserializes a PSBT while Bitcoin Core fails due to `ReadCompactSize(): size too large`. This failure happens during key type checking.

```cpp
// Type is compact size uint at beginning of key
SpanReader skey{key};
uint64_t type = ReadCompactSize(skey);
```

Base64: cHNidP8BABwAAAAFAAL9///+/wAAAAAALwBzYnT/AQAAAQEAdP90/wEAHAAAAAUAAv3///4B///Q////xgBzYnT/AQEAAC0AHAAx/3V0LakrcP8BdP8BAAAB/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD3/Mf91L62pK6k=

**Comment by hax0kartik** [comment]
Hello, I tried to find the root cause of this bug and there seem to be atleast 2 issues present:
1. Rust-Bitcoin seems to assume that `type_value` is [u8](https://github.com/rust-bitcoin/rust-bitcoin/blob/0ae6f49cea8276bc62d2d5c6e1fc710a66be81d3/bitcoin/src/psbt/raw.rs#L93) which is wrong. According to the documentation, it should be a [VarInt](https://en.bitcoin.it/wiki/BIP_0174)(check keytype documentation in specification)
2. [This check](https://github.com/bitcoin/bitcoin/blob/master/src/serialize.h#L363-L365) seems to be missing.

**Comment by brunoerg** [comment]
cc: @apoelstra

**Comment by apoelstra** [comment]
Thanks for finding this! I have subscribed to the repo so you hopefully won't need to ping me in future.

This looks reasonably straightforward to fix although it will involve prodding the `psbt` module which is in a state of limbo as we explore rewriting it.

**Comment by brunoerg** [comment]
Thank you, @apoelstra.

**Comment by brunoerg** [comment]
Closed as resolved. All impl has fixed it.
